export const HEADER_GRUPO_RUPTURA_57 = [
  "DIVISAO",
  "LOJA",
  "SEQPRODUTO",
  "DESCCOMPLETA",
  "CODFORN",
  "RAZAO",
  "STATUS",
  "MEDIAVENDAUNDIA",
  "MEDIAVENDAGP",
  "ESTOQUE",
  "PARMIN",
  "PARMAX",
  "PENDCPA",
  "EMBCPA",
  "CATEGORIA",
  "STATUS_COMPRA_CD1",
  "STATUS_COMPRA_CD2",
  "STATUS_COMPRA_CD3",
  "STATUS_COMPRA_CD4",
  "ESTQ_CD1",
  "ESTQ_CD2",
  "ESTQ_CD3",
  "ESTQ_CD4",
  "PENDCD_CD1",
  "PENDCD_CD2",
  "PENDCD_CD3",
  "PENDCD_CD4",
  "DIAS_ATIVACAOGERAL",
  "DATA_ATIVACAOGERAL",
  "DTA_ULTATIVACAO",
  "ULTIMA_ENTRADALOJA",
  "ULTIMA_SAIDALOJA",
  "DIAS_DA_COMPRALJ",
  "DIAS_DA_COMPRACD1",
  "DIAS_DA_COMPRACD2",
  "DIAS_DA_COMPRACD3",
  "DIAS_DA_COMPRACD4",
  "DIAS_RECEBTO_CD1",
  "DIAS_RECEBTO_CD2",
  "DIAS_RECEBTO_CD3",
  "DIAS_RECEBTO_CD4",
  "DIAS_RUPTURA",
  "ULTIMACPALOJA",
  "ULTIMACPACD1",
  "ULTIMACPACD2",
  "ULTIMACPACD3",
  "ULTIMACPACD4",
  "FAMILIA",
  "CUSTO_LIQUIDO",
  "EST_SELECINV_CD1",
  "EST_SELECINV_CD2",
  "EST_SELECINV_CD3",
  "EST_SELECINV_CD4",
  "DTA_ULTENTRADA_CD1",
  "DTA_ULTENTRADA_CD2",
  "DTA_ULTENTRADA_CD3",
  "DTA_ULTENTRADA_CD4",
] as const;

export type HeaderGrupoRupturaCol = (typeof HEADER_GRUPO_RUPTURA_57)[number];

export const INVENTARIO_COL_EMPRESA = "Código Empresa";
export const INVENTARIO_COL_PRODUTO = "Código Produto";
export const INVENTARIO_COL_QTD_SAIDA = "Qtd Saída Outras";

export const VALIDACAO_COL_LOJA = "Loja";
export const VALIDACAO_COL_ITEM = "Item";
export const VALIDACAO_COL_RUPTURA_MIX = "Qtd Item Ruptura no Mix";
export const VALIDACAO_COL_RUPTURA = "Qtd Item Ruptura";

export const VALIDACAO_SHEET_NAME = "Validaçao Ruptura";
