import type { MotorWorkflowFaseDefinicao } from "./motorWorkflowTypes.ts";

export const MOTOR_WORKFLOW_FASES: MotorWorkflowFaseDefinicao[] = [
  {
    id: "selecionar_regional_data",
    codigo: "F01",
    titulo: "Selecionar Regional e Data",
    descricao: "Define a regional piloto ou expandida e a data de referência do processamento.",
    objetivo: "Estabelecer o contexto regional e temporal para idempotência e organização no Drive.",
    oQueFazer: "Escolha a regional (MT, MS, DF, GO, SC, RS, SP ou MG) e informe a data de referência no formato YYYY-MM-DD.",
    arquivosNecessarios: [],
    preRequisitos: [],
    resultadoEsperado: ["Regional selecionada", "Data de referência definida", "Chave de idempotência preparada"],
    proximoPassoId: "enviar_arquivos_originais",
    acaoPrincipal: "Confirmar regional e data",
    ajudaContextual: "MT é a regional piloto. Todas as etapas seguintes dependem desta seleção.",
    mensagemSucesso: "Regional e data configuradas com sucesso.",
    mensagemErro: "Regional ou data inválida. Verifique o formato e tente novamente.",
    implementada: true,
    percentualImplementacao: 80,
  },
  {
    id: "enviar_arquivos_originais",
    codigo: "F02",
    titulo: "Enviar Arquivos Originais",
    descricao: "Recebe TXT padronizados e planilhas originais (XLS/XLSX/CSV) para a regional e data selecionadas.",
    objetivo: "Reunir todas as fontes necessárias antes da padronização e do parse.",
    oQueFazer: "Envie os arquivos para a pasta originais/ da regional no Drive (futuro) ou informe os caminhos locais.",
    arquivosNecessarios: [
      "1º Grupo de Ruptura.txt",
      "2º Grupo de CDs.txt",
      "Inventário Lojas.txt",
      "Validação Ruptura.xlsx",
      "Ordem CD´s.xlsx",
      "Compradores.xlsx",
      "Regras definidas.xlsx",
    ],
    preRequisitos: ["Regional selecionada", "Data de referência definida"],
    resultadoEsperado: ["Arquivos originais preservados sem alteração", "Lista de arquivos recebidos"],
    proximoPassoId: "validar_pacote_arquivos",
    acaoPrincipal: "Enviar arquivos",
    ajudaContextual: "Planilhas originais podem conter abas extras, fórmulas e resíduos — isso é esperado nesta etapa.",
    mensagemSucesso: "Arquivos originais recebidos.",
    mensagemErro: "Falha no envio. Verifique caminhos e permissões.",
    implementada: false,
    percentualImplementacao: 0,
  },
  {
    id: "validar_pacote_arquivos",
    codigo: "F03",
    titulo: "Validar Pacote de Arquivos",
    descricao: "Verifica presença, tipos e integridade básica do pacote de arquivos da regional.",
    objetivo: "Garantir que todos os pré-requisitos do processamento estão presentes antes da padronização.",
    oQueFazer: "Execute a validação do pacote e corrija arquivos ausentes ou com tipo incorreto.",
    arquivosNecessarios: ["Pacote completo de originais"],
    preRequisitos: ["Arquivos originais enviados"],
    resultadoEsperado: ["Relatório de validação do pacote", "Lista de pendências"],
    proximoPassoId: "padronizar_planilhas",
    acaoPrincipal: "Validar pacote",
    ajudaContextual: "TXT exige cabeçalho oficial. Planilhas serão padronizadas na fase seguinte.",
    mensagemSucesso: "Pacote validado.",
    mensagemErro: "Pacote incompleto ou inválido.",
    implementada: false,
    percentualImplementacao: 0,
  },
  {
    id: "padronizar_planilhas",
    codigo: "F04",
    titulo: "Padronizar Planilhas",
    descricao:
      "Transforma planilhas originais com abas, fórmulas e resíduos em arquivos limpos com layout oficial.",
    objetivo: "Produzir planilhas padrão consumíveis pelos parsers oficiais do Motor.",
    oQueFazer:
      "Execute `npm run motor:padronizar` para cada planilha não-TXT, informando regional, data, tipo e pasta de saída.",
    arquivosNecessarios: ["Planilhas originais XLS/XLSX/CSV"],
    preRequisitos: ["Regional selecionada", "Arquivo original enviado", "Tipo do arquivo reconhecido"],
    resultadoEsperado: [
      "Planilha padrão gerada",
      "Relatório de limpeza",
      "Duplicidades removidas registradas",
      "Linhas rejeitadas registradas",
      "Abas ignoradas registradas",
    ],
    proximoPassoId: "validar_planilhas_padronizadas",
    acaoPrincipal: "Padronizar planilhas",
    ajudaContextual:
      "Contratos preliminares — status aguardando validação com arquivo real (Fase 2C.2.3). Original nunca é sobrescrito.",
    mensagemSucesso: "Planilha padronizada com sucesso.",
    mensagemErro: "Falha na padronização. Consulte o relatório de erros.",
    implementada: true,
    percentualImplementacao: 70,
  },
  {
    id: "validar_planilhas_padronizadas",
    codigo: "F05",
    titulo: "Validar Planilhas Padronizadas",
    descricao: "Confirma que as planilhas padrão atendem aos contratos oficiais antes do parse.",
    objetivo: "Evitar que parsers consumam arquivos incompletos ou fora do layout.",
    oQueFazer: "Revise o relatório de padronização e execute validação de contrato.",
    arquivosNecessarios: ["Planilhas motor_*_padrao.xlsx"],
    preRequisitos: ["Padronização concluída"],
    resultadoEsperado: ["Contrato validado", "Avisos documentados"],
    proximoPassoId: "executar_parser",
    acaoPrincipal: "Validar planilhas padrão",
    ajudaContextual: "Ordem dos CDs padronizada (motor_ordem_cds_padrao.xlsx) validada na Fase 2C.2.3 — pré-requisito da Centralização.",
    mensagemSucesso: "Planilhas padronizadas validadas.",
    mensagemErro: "Planilha padrão não atende ao contrato.",
    implementada: true,
    percentualImplementacao: 60,
  },
  {
    id: "executar_parser",
    codigo: "F06",
    titulo: "Executar Parser",
    descricao: "Executa parsers oficiais sobre TXT validados e planilhas padronizadas.",
    objetivo: "Ler e normalizar dados brutos em estruturas tipadas do Motor.",
    oQueFazer: "Execute `npm run motor:parse` para cada arquivo com regional e data.",
    arquivosNecessarios: ["TXT oficiais", "Planilhas padronizadas"],
    preRequisitos: ["Planilhas padronizadas validadas", "TXT com cabeçalho válido"],
    resultadoEsperado: ["Linhas parseadas", "Erros de parse documentados"],
    proximoPassoId: "executar_transformacoes",
    acaoPrincipal: "Executar parser",
    ajudaContextual: "Parsers TXT existentes (Fase 2A). Planilhas só após padronização.",
    mensagemSucesso: "Parser executado com sucesso.",
    mensagemErro: "Erros críticos no parse.",
    implementada: true,
    percentualImplementacao: 85,
  },
  {
    id: "executar_transformacoes",
    codigo: "F07",
    titulo: "Executar Transformações",
    descricao: "Aplica transformações tipadas sobre dados parseados.",
    objetivo: "Normalizar tipos, deduplicar e preparar entradas para o BRE.",
    oQueFazer: "Processar transformações via serviço do Motor.",
    arquivosNecessarios: ["Saída do parser"],
    preRequisitos: ["Parser executado"],
    resultadoEsperado: ["Produtos loja normalizados", "CD5 mapeado", "Inventário agrupado"],
    proximoPassoId: "executar_bre",
    acaoPrincipal: "Executar transformações",
    ajudaContextual: "Inclui parse de datas BR, decimais com vírgula e deduplicação por chave.",
    mensagemSucesso: "Transformações concluídas.",
    mensagemErro: "Falha nas transformações.",
    implementada: true,
    percentualImplementacao: 85,
  },
  {
    id: "executar_bre",
    codigo: "F08",
    titulo: "Executar BRE",
    descricao:
      "Aplica regras de negócio: classificação CP/MP/LP, Dias Pedido, ações operacionais e Centralização (Fase 2C.3).",
    objetivo: "Produzir resultado operacional por loja/produto incluindo ordem CDs, menor recebimento e status derivados.",
    oQueFazer: "Executar processarBre com catálogos padronizados (motor_ordem_cds_padrao.xlsx).",
    arquivosNecessarios: ["Entrada BRE", "Catálogos padronizados"],
    preRequisitos: ["Transformações concluídas", "Ordem CDs padronizada validada"],
    resultadoEsperado: [
      "MotorBreItemResultado por item",
      "Menor Recebto CD, Produto Centralizado, flags 1ºCD..5ºCD",
      "Status Recebto, Status Estoque CDs, Status Solicitação Ativação CD",
    ],
    proximoPassoId: "validar_excel_v7",
    acaoPrincipal: "Executar BRE",
    ajudaContextual:
      "Centralização consome somente motor_ordem_cds_padrao.xlsx — nunca Centralizados.txt nem planilha original.",
    mensagemSucesso: "BRE executado com centralização.",
    mensagemErro: "Dependência bloqueada ou erro de regra.",
    implementada: true,
    percentualImplementacao: 85,
  },
  {
    id: "validar_excel_v7",
    codigo: "F09",
    titulo: "Validar Excel × V7",
    descricao: "Compara saída V7 com fixtures/export Excel com zero tolerância textual onde aplicável.",
    objetivo: "Garantir fidelidade ao Power Query.",
    oQueFazer: "Execute testes compareExcelV7 e analise divergências.",
    arquivosNecessarios: ["Fixtures Excel", "Saída BRE"],
    preRequisitos: ["BRE executado"],
    resultadoEsperado: ["Relatório de divergências", "Campos iguais documentados"],
    proximoPassoId: "publicar_data_mart",
    acaoPrincipal: "Comparar Excel × V7",
    ajudaContextual: "Campos não implementados aparecem como não comparáveis.",
    mensagemSucesso: "Comparação concluída sem divergências críticas.",
    mensagemErro: "Divergências encontradas.",
    implementada: true,
    percentualImplementacao: 70,
  },
  {
    id: "publicar_data_mart",
    codigo: "F10",
    titulo: "Publicar Data Mart",
    descricao: "Publica dados consolidados para consumo analítico.",
    objetivo: "Disponibilizar camada de dados para indicadores e views.",
    oQueFazer: "Aguardar autorização e implementação da Fase de Data Mart.",
    arquivosNecessarios: ["Saída BRE validada"],
    preRequisitos: ["Excel × V7 validado"],
    resultadoEsperado: ["Data Mart publicado"],
    proximoPassoId: "gerar_indicadores",
    acaoPrincipal: "Publicar Data Mart",
    ajudaContextual: "Não implementado nesta fase.",
    mensagemSucesso: "Data Mart publicado.",
    mensagemErro: "Data Mart não disponível.",
    implementada: false,
    percentualImplementacao: 0,
  },
  {
    id: "gerar_indicadores",
    codigo: "F11",
    titulo: "Gerar Indicadores",
    descricao: "Calcula indicadores operacionais a partir do Data Mart.",
    objetivo: "Produzir KPIs de ruptura por regional.",
    oQueFazer: "Aguardar implementação futura.",
    arquivosNecessarios: ["Data Mart"],
    preRequisitos: ["Data Mart publicado"],
    resultadoEsperado: ["Indicadores gerados"],
    proximoPassoId: "liberar_views",
    acaoPrincipal: "Gerar indicadores",
    ajudaContextual: "Não implementado nesta fase.",
    mensagemSucesso: "Indicadores gerados.",
    mensagemErro: "Indicadores não disponíveis.",
    implementada: false,
    percentualImplementacao: 0,
  },
  {
    id: "liberar_views",
    codigo: "F12",
    titulo: "Liberar Views",
    descricao: "Disponibiliza views SQL ou equivalentes para consumo.",
    objetivo: "Expor dados filtrados por regional e data.",
    oQueFazer: "Aguardar implementação futura.",
    arquivosNecessarios: ["Indicadores"],
    preRequisitos: ["Indicadores gerados"],
    resultadoEsperado: ["Views liberadas"],
    proximoPassoId: "disponibilizar_modulos",
    acaoPrincipal: "Liberar views",
    ajudaContextual: "Não implementado nesta fase.",
    mensagemSucesso: "Views liberadas.",
    mensagemErro: "Views não disponíveis.",
    implementada: false,
    percentualImplementacao: 0,
  },
  {
    id: "disponibilizar_modulos",
    codigo: "F13",
    titulo: "Disponibilizar aos Módulos",
    descricao: "Integra resultados do Motor aos módulos consumidores (UI, relatórios, etc.).",
    objetivo: "Entregar valor operacional ao usuário final.",
    oQueFazer: "Aguardar implementação de UI e integrações.",
    arquivosNecessarios: ["Views", "Indicadores"],
    preRequisitos: ["Views liberadas"],
    resultadoEsperado: ["Módulos consumindo dados do Motor"],
    proximoPassoId: null,
    acaoPrincipal: "Disponibilizar módulos",
    ajudaContextual: "UI autoexplicativa futura usará este catálogo de fases.",
    mensagemSucesso: "Dados disponíveis aos módulos.",
    mensagemErro: "Integração indisponível.",
    implementada: false,
    percentualImplementacao: 0,
  },
];

export function obterFasePorId(id: MotorWorkflowFaseDefinicao["id"]): MotorWorkflowFaseDefinicao {
  const fase = MOTOR_WORKFLOW_FASES.find((f) => f.id === id);
  if (!fase) throw new Error(`Fase não encontrada: ${id}`);
  return fase;
}
