import type { MotorProdutoLojaConsolidado } from "../consolidar/consolidacaoTypes.ts";

/** Mapeia consolidado V7 → campos comparáveis com Excel/Power Query. */
export function mapConsolidadoParaCompare(
  item: MotorProdutoLojaConsolidado,
): Record<string, string | number | boolean | null> {
  return {
    LOJA: item.loja,
    SEQPRODUTO: item.seqproduto,
    DESCCOMPLETA: item.descricao,
    RAZAO: item.fornecedor,
    Rede: item.rede,
    COMPRADOR: item.comprador,
    "Base Limpa": item.baseLimpa,
    "Menor que três Unidades": item.ruptura104c ? 1 : 0,
    "Ruptura Inventário": item.rupturaComInventario,
    "Ruptura Sem Inventário": item.rupturaSemInventario,
    "Inventário (Unid)": item.inventarioUnid,
    Soma_EstoqueCD: item.somaEstoqueCd,
    Cross: item.crossSum,
    "Cross Docking": item.crossDocking,
    "Curto Prazo": item.curtoPrazo,
    "Médio Prazo": item.medioPrazo,
    "Longo Prazo": item.longoPrazo,
    "Pendência Cpa CD": item.pendenciaCpaCd,
    "Dias Pedido": item.diasPedido,
    "Média dias Pedido Lj": item.diasCompraCd1,
    "Média dias Pedido cd1": item.diasCompraCd1,
    "Média dias Pedido cd2": item.diasCompraCd2,
    "Média dias Pedido cd3": item.diasCompraCd3,
    "Média dias Pedido cd4": item.diasCompraCd4,
    "Média dias Pedido cd5": item.diasCompraCd5,
    "Ação Curto Prazo": item.acaoCurtoPrazo,
    "Ação Médio Prazo": item.acaoMedioPrazo,
    "Menor Recebto CD": item.menorDiasRecebimento,
    Centralizado: item.produtoCentralizado,
    "Produto Centralizado": item.textoProdutoCentralizado,
    "1ºCD": item.flagPrimeiroCd,
    "2ºCD": item.flagSegundoCd,
    "3ºCD": item.flagTerceiroCd,
    "4ºCD": item.flagQuartoCd,
    "5ºCD": item.flagQuintoCd,
    "Status Recebto": item.statusRecebto,
    "Status Estoque CDs": item.statusEstoqueCds,
    "Status Solicitação Ativação CD": item.statusSolicitacaoAtivacaoCd,
    statusOperacional: item.statusOperacional,
    qualidadeDados: item.qualidadeDados,
  };
}

export const CAMPOS_PILOTO_COMPARE: { campo: string; toleranciaDecimal?: number }[] = [
  { campo: "LOJA" },
  { campo: "SEQPRODUTO" },
  { campo: "DESCCOMPLETA" },
  { campo: "RAZAO" },
  { campo: "Rede" },
  { campo: "COMPRADOR" },
  { campo: "Base Limpa" },
  { campo: "Menor que três Unidades" },
  { campo: "Ruptura Inventário" },
  { campo: "Ruptura Sem Inventário" },
  { campo: "Inventário (Unid)" },
  { campo: "Soma_EstoqueCD" },
  { campo: "Cross Docking" },
  { campo: "Curto Prazo" },
  { campo: "Médio Prazo" },
  { campo: "Longo Prazo" },
  { campo: "Pendência Cpa CD" },
  { campo: "Dias Pedido" },
  { campo: "Ação Curto Prazo" },
  { campo: "Ação Médio Prazo" },
  { campo: "Menor Recebto CD" },
  { campo: "Produto Centralizado" },
  { campo: "1ºCD" },
  { campo: "2ºCD" },
  { campo: "3ºCD" },
  { campo: "4ºCD" },
  { campo: "5ºCD" },
  { campo: "Status Recebto" },
  { campo: "Status Estoque CDs" },
  { campo: "Status Solicitação Ativação CD" },
  { campo: "Média dias Pedido Lj", toleranciaDecimal: 0.01 },
  { campo: "Média dias Pedido cd1", toleranciaDecimal: 0.01 },
  { campo: "Média dias Pedido cd2", toleranciaDecimal: 0.01 },
  { campo: "Média dias Pedido cd3", toleranciaDecimal: 0.01 },
  { campo: "Média dias Pedido cd4", toleranciaDecimal: 0.01 },
  { campo: "Média dias Pedido cd5", toleranciaDecimal: 0.01 },
];
